version: 2.1

executors:
  golang:
    working_directory: /go/src/moul.io/multipmuri
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"

orbs:
  moul: moul/build@1.4.0
  codecov: codecov/codecov@1.0.2

jobs:
  go-build:
    executor: golang
    steps:
      - checkout
      - moul/install_retry
      - run: retry -m 3 go mod download
      - run: retry -m 3 make test
      - moul/install_golangci-lint
      - run: PATH=$PATH:$(pwd)/bin retry -m 3 make lint
      - codecov/upload:
          file: coverage.txt

workflows:
  main:
    jobs:
      - go-build
